In [1]:
from __future__ import print_function
from __future__ import absolute_import
from __future__ import division

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

/Users/z002krv/anaconda3/envs/TensorFlow_RB/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.mlab import  PCA

In [4]:
print(tf.__version__)
print(np.__version__)
print(pd.__version__)

1.9.0
1.14.3
0.23.0


In [5]:
prices = pd.read_csv('stocks.csv')

In [6]:
prices.head()

Date        ADBE         CVX       MDLZ        NFLX       ORCL  \
0  3-Jan-17  113.820000  110.759811  44.430000  141.220001  40.230000   
1  1-Dec-16  102.949997  116.584061  44.330002  123.800003  38.299999   
2  1-Nov-16  102.809998  110.502274  41.066032  117.000000  40.033211   
3  3-Oct-16  107.510002  102.728424  44.750420  124.870003  38.270115   
4  1-Sep-16  108.540001  100.933739  43.714809   98.550003  38.975769   

        SBUX  
0  55.649239  
1  55.270943  
2  57.709953  
3  52.588333  
4  53.648621

In [7]:
prices.Date = pd.to_datetime(prices.Date , infer_datetime_format=True)

In [8]:
prices = prices.sort_values(['Date'],ascending=[True])

In [9]:
prices.head()

Date       ADBE        CVX       MDLZ      NFLX       ORCL  \
120 2007-01-03  38.869999  50.777351  17.519524  3.258571  15.696321   
119 2007-02-01  39.250000  48.082939  16.019426  3.218571  15.028588   
118 2007-03-01  41.700001  51.900383  16.009354  3.312857  16.583584   
117 2007-04-02  41.560001  54.588032  16.924608  3.167143  17.196436   
116 2007-05-01  44.060001  57.598267  17.111704  3.128572  17.726965   

          SBUX  
120  15.752188  
119  13.930813  
118  14.138198  
117  13.984914  
116  12.988567

In [10]:
prices = prices[['ADBE','MDLZ','SBUX']]

In [11]:
prices.head()

ADBE       MDLZ       SBUX
120  38.869999  17.519524  15.752188
119  39.250000  16.019426  13.930813
118  41.700001  16.009354  14.138198
117  41.560001  16.924608  13.984914
116  44.060001  17.111704  12.988567

In [12]:
prices.dtypes

ADBE    float64
MDLZ    float64
SBUX    float64
dtype: object

In [13]:
dict(prices.dtypes)

{'ADBE': dtype('float64'), 'MDLZ': dtype('float64'), 'SBUX': dtype('float64')}

In [14]:
returns = prices[[key for key in dict(prices.dtypes) if dict(prices.dtypes)[key] in ['float64','int64']]].pct_change()

In [15]:
returns = returns[1:]

In [16]:
returns.head()

ADBE      MDLZ      SBUX
119  0.009776 -0.085624 -0.115627
118  0.062420 -0.000629  0.014887
117 -0.003357  0.057170 -0.010842
116  0.060154  0.011055 -0.071244
115 -0.088743  0.049031 -0.089205

In [17]:
returns_arr= returns.as_matrix()[:10]

/Users/z002krv/anaconda3/envs/TensorFlow_RB/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [18]:
returns_arr

array([[ 0.0097762 , -0.08562436, -0.11562679],
       [ 0.06242041, -0.00062874,  0.01488678],
       [-0.00335731,  0.05716995, -0.01084183],
       [ 0.06015399,  0.01105467, -0.07124441],
       [-0.0887426 ,  0.04903135, -0.08920514],
       [ 0.0034869 , -0.07092208,  0.01676833],
       [ 0.06105731, -0.02106854,  0.03260863],
       [ 0.02128655,  0.08540859, -0.04900176],
       [ 0.09711411, -0.0318747 ,  0.01832061],
       [-0.12025058,  0.03412141, -0.12331339]])

In [19]:
from sklearn.preprocessing import  StandardScaler
scaler = StandardScaler()

In [20]:
returns_arr_scaled= scaler.fit_transform(returns_arr)

In [21]:
returns_arr_scaled

array([[-0.00794824, -1.66841975, -1.3815757 ],
       [ 0.79937034, -0.06227426,  0.93127707],
       [-0.20935564,  1.02993615,  0.47533596],
       [ 0.76461402,  0.15850482, -0.59506817],
       [-1.51877095,  0.87614265, -0.91335326],
       [-0.10439707, -1.39059372,  0.96462026],
       [ 0.7784667 , -0.44852127,  1.24532886],
       [ 0.16856723,  1.56355606, -0.20090235],
       [ 1.33141124, -0.65272298,  0.99212851],
       [-2.00195763,  0.59439231, -1.51779118]])

In [22]:
results = PCA(returns_arr_scaled,standardize=False)

/Users/z002krv/anaconda3/envs/TensorFlow_RB/lib/python3.6/site-packages/ipykernel_launcher.py:1: MatplotlibDeprecationWarning: The PCA class was deprecated in version 2.2.
  """Entry point for launching an IPython kernel.


In [23]:
results.fracs

array([0.61673564, 0.2826719 , 0.10059245])

In [24]:
np.dot(results.Y,results.Wt)

array([[-0.00794824, -1.66841975, -1.3815757 ],
       [ 0.79937034, -0.06227426,  0.93127707],
       [-0.20935564,  1.02993615,  0.47533596],
       [ 0.76461402,  0.15850482, -0.59506817],
       [-1.51877095,  0.87614265, -0.91335326],
       [-0.10439707, -1.39059372,  0.96462026],
       [ 0.7784667 , -0.44852127,  1.24532886],
       [ 0.16856723,  1.56355606, -0.20090235],
       [ 1.33141124, -0.65272298,  0.99212851],
       [-2.00195763,  0.59439231, -1.51779118]])

In [25]:
n_inputs  = 3
n_hidden = 2
n_outouts = n_inputs

In [26]:
X  = tf.placeholder(tf.float32 , shape = [None,n_inputs])

In [27]:
hidden = tf.layers.dense(X,n_hidden)

In [28]:
output = tf.layers.dense(hidden,n_outouts)

In [29]:
reconstruction_loss = tf.reduce_mean(tf.square(output-X))

In [30]:
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)

In [31]:
training_op = optimizer.minimize(reconstruction_loss)

In [32]:
#tf.reset_default_graph()

In [33]:
init = tf.global_variables_initializer()

In [34]:
n_iter = 10000

In [35]:
with tf.Session() as sess:
    init.run()
    for iter in range(n_iter):
            training_op.run(feed_dict={X:returns_arr_scaled})
            
    outputs_val = output.eval(feed_dict={X:returns_arr_scaled})
    print(outputs_val)

[[-0.4490621  -1.7773783  -0.9831107 ]
 [ 0.8298887  -0.05469791  0.9036716 ]
 [-0.00454278  1.0805607   0.29044044]
 [ 0.05007089 -0.01799638  0.05049707]
 [-1.2644243   0.9389866  -1.1428841 ]
 [ 0.5983972  -1.216936    0.329614  ]
 [ 1.0220679  -0.38830045  1.0251796 ]
 [-0.22358955  1.4666971   0.15355702]
 [ 1.1854469  -0.68874186  1.1238751 ]
 [-1.7440054   0.65812033 -1.7505531 ]]


In [38]:
np.dot(results.Y[:,[0,1]],results.Wt[[0,1]])

array([[-0.44903258, -1.77738749, -0.98310396],
       [ 0.82990699, -0.05473033,  0.90369053],
       [-0.00461448,  1.08051646,  0.29037459],
       [ 0.05004494, -0.01802601,  0.05046729],
       [-1.2645507 ,  0.93894653, -1.14301362],
       [ 0.59845995, -1.21695631,  0.32966536],
       [ 1.0221117 , -0.38832995,  1.02522209],
       [-0.2236927 ,  1.46665014,  0.15346185],
       [ 1.18550953, -0.68876729,  1.12393484],
       [-1.74414266,  0.65808424, -1.75069897]])